### ISSUE TITLE
App crashes when you dont set the "iconKey"

### ISSUE THREAD

**Issue by brunomb** [guilhermesgb/ShiftableEditText#17]
Stack Trace: 

> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicHeight()' on a null object reference
>             at com.github.guilhermesgb.marqueeto.LabelledMarqueeEditText.enableEditMode(LabelledMarqueeEditText.java:491)
>             at com.github.guilhermesgb.marqueeto.LabelledMarqueeEditText.initEditAndMarqueeViews(LabelledMarqueeEditText.java:281)
>             at com.github.guilhermesgb.marqueeto.LabelledMarqueeEditText.<init>(LabelledMarqueeEditText.java:113)
>             at com.github.guilhermesgb.marqueeto.LabelledMarqueeEditText.<init>(LabelledMarqueeEditText.java:97)
>             at java.lang.reflect.Constructor.newInstance(Native Method)
>             at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
>             at android.view.LayoutInflater.createView(LayoutInflater.java:607)
>             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
>             at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
>             at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
>             at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
>             at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
>             at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
>             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
>             at br.com.jfl.activity.TempInputActivity.onCreate(TempInputActivity.java:28)
>             at android.app.Activity.performCreate(Activity.java:5990)
>             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
>             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
>             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
>             at android.app.ActivityThread.access$800(ActivityThread.java:151)
>             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
>             at android.os.Handler.dispatchMessage(Handler.java:102)
>             at android.os.Looper.loop(Looper.java:135)
>             at android.app.ActivityThread.main(ActivityThread.java:5257)
>             at java.lang.reflect.Method.invoke(Native Method)
>             at java.lang.reflect.Method.invoke(Method.java:372)
>             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
>             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by xibaca** [comment]
Reopening to work on a proper fix.
